name: Charm Lib Checker
description: >
  Detect and notify on drifts in charm libraries.
  This action is designed to be used for pull requests.

inputs:
  charm_path:
    default: "."
    description: >
      Path to the charm to fetch libs for, if different.
  github_token:
    required: true
    description: >
      GitHub secret used to post to the pull request checked.

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo snap install yq
      shell: bash
    - name: Detect drift
      id: detect
      run: |
        cd ${{ inputs.charm_path }}
        export CHARM_NAME=$(yq eval '.name' metadata.yaml | sed 's/-/_/')
        charmcraft fetch-lib 2>&1 | sed "/$CHARM_NAME/d" | grep -E '(updated to version|not found in Charmhub|has local changes)' && echo "::set-output name=WARN::true" || echo "No drifts detected"
      shell: bash
    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: ${{ (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && steps.detect.outputs.WARN == 'true' }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({
            issue_number, 
            owner, 
            repo, 
            body: 'Libraries are not up to date with their remote counterparts. ' +
                  'If this was not intentional, run \`charmcraft fetch-libs\` and commit the updated libs to your PR branch.'
          });