name: Charm Lib Checker
description: >
  Detect and notify on drifts in charm libraries.
  This action only works with pull requests.

inputs:
  charm_path:
    default: "."
    description: >
      Path to the charm to fetch libs for, if different.
  github_token:
    required: true
    description: >
      GitHub secret used to post to the pull request checked.

runs:
  using: "composite"
  steps:
    - name: Detect drift
      run: |
        cd ${{ inputs.charm_path }}
        out=$(charmcraft fetch-lib 2>&1 | grep -E "(updated\sto\sversion|not found in Charmhub|has local changes)")
        body="The libraries used in this pull request are not in sync with their remote counterparts:\n\n\`\`\`$out\`\`\`"
        echo "body=$body" >> $GITHUB_ENV
      shell: bash
    - name: PR Comment
      uses: actions/github-script@v2
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{env.body}}'
          })
