name: Charm Lib Checker
description: >
  Detect and notify on drifts in charm libraries.
  This action only works with pull requests.

inputs:
  charm_path:
    default: "."
    description: >
      Path to the charm to fetch libs for, if different.
  github_token:
    required: true
    description: >
      GitHub secret used to post to the pull request checked.

runs:
  using: "composite"
  steps:
    - name: Detect drift
      run: |
        charmcraft \
          -p ${{ inputs.charm_path }} \
          fetch-lib 
        # | \ grep -E "(updated\sto\sversion|not found in Charmhub|has local changes)"
      shell: bash
    - name: Add warning
      if: ${{ failure() }}
      run: |
        export TEXT="Libraries are not up to date with their remote counterparts. If this was not intentional, run \`charmcraft fetch-libs\` and commit the updated libs to your PR branch."
        echo "::warning file=metadata.yaml,line=1,col=1::$TEXT"  
      shell: bash