name: Charm Lib Checker
description: >
  Detect and notify on drifts in charm libraries.
  This action only works with pull requests.

inputs:
  charm_path:
    default: "."
    description: >
      Path to the charm to fetch libs for, if different.
  github_token:
    required: true
    description: >
      GitHub secret used to post to the pull request checked.

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo snap install yq
      shell: bash
    - name: Detect drift
      run: |
        cd ${{ inputs.charm_path }}
        export TEXT="Libraries are not up to date with their remote counterparts. If this was not intentional, run \`charmcraft fetch-libs\` and commit the updated libs to your PR branch."
        export CHARM_NAME=$(yq eval '.name' metadata.yaml | sed 's/-/_/')
        charmcraft fetch-lib 2>&1 | sed "/$CHARM_NAME/d" | grep -E '(updated to version|not found in Charmhub|has local changes)' && echo "::warning file=metadata.yaml,line=1,col=1::$TEXT"
      shell: bash