name: Charm Lib Checker
description: >
  Detect and notify on drifts in charm libraries.
  This action only works with pull requests.
inputs:
  github_secret:
    required: true
    description: >
      GitHub secret used to post to the pull request checked.

runs:
  using: "composite"
  steps:
    - name: Detect drift
      run: |
        out=$(charmcraft fetch-lib 2>&1 | grep -E "(updated\sto\sversion|not found in Charmhub|has local changes)")
        body=" ⚠️  The libraries used in this PR are not in sync with their remote counterparts:\n\\n`\`\`$OUT\`\`\`"
        curl \
          -X POST \
          -H 'authorization: Bearer ${{ inputs.github_secret }}' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/simskij/charm-lib-checkeer-action/issues/1/comments \
          -d "{\"body\":\"$body\"}"
      shell: bash
